### ISSUE TITLE
learn_init=True causes cycles in Theano graph with multiple LSTM layers

### ISSUE THREAD

**Issue by craffel** [craffel/nntools#11]
As reported in #9, the following minimal example causes a Theano `ValueError: graph contains cycles`:

``` Python
import lasagne
import theano.tensor as T
import theano

l_in = lasagne.layers.InputLayer(shape=(4, 5, 6))
l_fwd_1 = lasagne.layers.LSTMLayer(l_in, 10, learn_init=True)
l_fwd_2 = lasagne.layers.RecurrentLayer(l_fwd_1, 12)
l_bck_2 = lasagne.layers.RecurrentLayer(l_fwd_1, 12)
l_sum_2 = lasagne.layers.ElemwiseSumLayer([l_fwd_2, l_bck_2])

input = T.tensor3('input')
target_output = T.tensor3('target_output')

cost = T.mean((l_sum_2.get_output(input) - target_output)**2)
all_params = lasagne.layers.get_all_params(l_sum_2)
updates = lasagne.updates.nesterov_momentum(cost, all_params, .1)

train = theano.function([input, target_output], cost, updates=updates)
```

This appears to only be true when there's an `LSTMLayer` with `learn_init=True` which is connected through other layers to a `MultipleInputsLayer`.

**Comment by JackKelly** [comment]
just confirming that I can now train multi-layered LSTM networks if `learn_init=False`.  Thanks.

**Comment by craffel** [comment]
I made the minimum example above a bit more concise.  This doesn't appear to happen when there `learn_init=True` layer is a `RecurrentLayer`.

**Comment by craffel** [comment]
Some interesting things - 
- In order to reproduce this, an `LSTMLayer` with `learn_init=True` must be connected through two layers (of any kind, even a layers which do a simple pass-through) to a `MultipleInputsLayer`
- The main thing `learn_init=True` does is return `self.hid_init` and `self.cell_init` as params in `get_all_params`.  If the `LSTMLayer` is changed so that it only includes `self.hid_init` in the params (like a `RecurrentLayer`), this bug doesn't happen.
- This only happens when `device=gpu`.

So, this appears to have to do specifically with learning _cell_ initialization (not just any initialization) when there's two "parallel" paths in the network graph (i.e. there's a `MultipleInputsLayer`) and the device is the GPU.  I have no idea why at this point.

**Comment by skaae** [comment]
Checked @craffels examples with the code from https://github.com/craffel/nntools/pull/27 (https://github.com/skaae/nntools/commit/f6048bfe057255fc45d7e42634772821a8e9dddf) 

It don't see any error about cycles using the GPU.

**Comment by craffel** [comment]
Thanks presumably to some of the recent changes, this doesn't appear to be a bug any more.
