### ISSUE TITLE
Init size dependent batch size

### ISSUE THREAD

**Issue by skaae** [craffel/nntools#17]
The size of the hid init and cell init is dependent on the batch size. I havent got a nice solutions but i think the correct thing would be to have a single init vectors that are repeated num batch times? 

https://github.com/craffel/nntools/blob/master/lasagne/layers/recurrent.py#L445

One possible solution is 

``` PYTHON
# weight setup
self.cell_init = self.create_param(cell_init, (1, num_units))
self.hid_init = self.create_param(hid_init, (1, num_units))


#scan setup
ones = T.ones((self.num_batch,1))
init = [T.dot(ones, cell_init), T.dot(ones, hid_init)]
```

**Comment by craffel** [comment]
Oh, good call, I think this could actually be considered a bug because there should only be a single init vector used across all examples.  It should be possible with broadcasting instead of doing a dot against ones which will be more efficient.  I will try to fix this soon.

**Comment by skaae** [comment]
I guess it is a bug, but I dont know if it matters in practice :) 
The bug has the slightly annoing side effect that you cannot recompile your saved model to a new batch size.
