### ISSUE TITLE
Default bias initialization in forget gate

### ISSUE THREAD

**Issue by pedromnasc** [craffel/nntools#19]
Why the default bias initialization in forget gate is so small (b_forgetgate=init.Normal(0.1))? Here : http://www.cs.utoronto.ca/~ilya/pubs/ilya_sutskever_phd_thesis.pdf is stated the following: 
"We have included an explicit bias bf for the forget gates because it is important for them to be
approximately 1 at the early stages of learning, which is accomplished by initializing bf to a large value
(such as 5). If it is not done, it will be harder to learn long range dependencies because the smaller
values of the forget gates will create a vanishing gradients problem".

Am i missing something? 
Thanks in advance.

**Comment by craffel** [comment]
No real reason.  I think I was initially trying to match rnnlib/currennt.  If you want to set it to something else, just pass in a different `lasagne.init` instance (e.g. `lasagne.init.Constant(5.)`).
