### ISSUE TITLE
Apply nonlinearity once in RecurrentLayer? 

### ISSUE THREAD

**Issue by JackKelly** [craffel/nntools#21]
Thanks again for all your work on Lasagne; it's a great tool.  And forgive me if this is a dumb question...

`RecurrentLayer.__init__()` sets `in_to_hid` and `hid_to_hid` to both be `DenseLayers` with the same nonlinearity as `RecurrentLayer.nonlinearity`.  But then we apply `nonlinearity` _again_ in the `step` function:

``` python
        # Create single recurrent computation step function
        def step(layer_input, hid_previous):
            return self.nonlinearity(
                self.input_to_hidden.get_output(layer_input) +
                self.hidden_to_hidden.get_output(hid_previous))
```

My question is: should we instead only apply the nonlinearity once, in `step`? i.e. `RecurrentLayer.__init__()` would set `in_to_hid` and `hid_to_hid` to have `nonlinearity=linear`?

**Comment by craffel** [comment]
Hmm, yeah, that makes sense.  The intention/correct behavior is that  `in_to_hid` and `hid_to_hid` should have `nonlinearity=None`.  I'll change this now.

**Comment by JackKelly** [comment]
nice, thanks ;)
