### ISSUE TITLE
slicing layer

### ISSUE THREAD

**Issue by skaae** [craffel/nntools#31]
Add slicing layer.

I started writing the slicing layer.  I think it should have the arguments:
- `slice_indices`
- `slice_dimension`

So `slice indices=(1,3)` and `slice_dimension=2` would return `x[:, :, 1:3]`

Do you know how to generalize this to any dimension without writing a ton of if statements.

**Comment by benanne** [comment]
Maybe the interface of this layer should use actual slice objects? Numpy arrays actually support indexing with a list of slice objects, e.g.:

``` python
>>> import numpy as np
>>> d = np.zeros((2,3,4,5,6))
>>> idx = [slice(None), slice(None), slice(2, 3), slice(2, 5)]
>>> d[idx].shape
(2, 3, 1, 3, 6)
```

I don't know how well Theano supports this though.

**Comment by skaae** [comment]
Yes. That would simplify the code. I'll give it a go and move the PR to lasagne.

**Comment by f0k** [comment]
I'd just use `indices` and `axis` for the parameter names, and allow `indices` to be either a slice object or a tuple.

> Do you know how to generalize this to any dimension without writing a ton of if statements.

``` python
def __init__(self, incoming, indices, axis=-1, **kwargs):
    super(SliceLayer, self).__init__(incoming, **kwargs)
    self.slice = indices if isinstance(indices, slice) else slice(*indices)
    self.axis = axis
def get_output_for(self, input):
    axis = self.axis
    if axis < 0:
        axis += input.ndim
    return input[(slice(None),) * axis + (self.slice,)]
```

/edit: `get_output_shape_for` is manageable as well. Something like:

``` python
def get_output_shape_for(self, input_shape):
    output_shape = list(input_shape)
    output_shape[self.axis] = len(range(*self.slice.indices(input_shape[self.axis])))
    return tuple(output_shape)
```

But `len(range(...))` is a waste of resources in Python 2, maybe there's a better way.

**Comment by skaae** [comment]
Im struggling a bit with your code.

``` Python
    def __init__(self, incoming, indices, axis=-1, **kwargs):
        super(SliceLayer, self).__init__(incoming, **kwargs)

    # support for ints    
    if isinstance(indices, int):
            indices = slice(indices, indices + 1)

        self.slice = indices if isinstance(indices, slice) else slice(*indices)
        self.axis = axis

    def get_output_shape_for(self, input_shape):
        output_shape = list(input_shape)
        sliced_size = len(range(*self.slice.indices(input_shape[self.axis])))

        if sliced_size > 1:
            output_shape[self.axis] = sliced_size
        else:
            del output_shape[self.axis]
        return tuple(output_shape)

    def get_output_for(self, input):
        axis = self.axis
        if axis < 0:
            axis += input.ndim
        return input[(slice(None),) * axis + (self.slice,)]
```

So far if have just added support for integers. I would like singleton dimensions to be squeezed. Is that possible? 

```
in_shp = (3, 5, 2)
l_inp = InputLayer(in_shp)
l_slice_ax0 = SliceLayer(l_inp, axis=0, indices=0)

x = numpy.arange(numpy.prod(in_shp)).reshape(in_shp).astype('float32')
x1 = x[0]
assert get_output_shape(l_slice_ax0) == x1.shape
```

The assert is not true because the output dimension is `(1, 5, 2)`

And I would like i to return `(5, 2)`

**Comment by skaae** [comment]
I accidently closed the issue. Please see the question in the above comment.

**Comment by f0k** [comment]
I would suggest to only squeeze the dimension if `indices` really is an int. That's in line with how numpy behaves:

```
>>> import numpy as np
>>> x = np.zeros((3, 5, 2))
>>> x[0:1].shape
(1, 5, 2)
>>> x[0].shape
(5, 2)
```

So if `indices` is an int, just set `self.slice` to that int directly. In `get_output_for`, nothing needs to change then, and in `get_output_shape_for`, you would check if `self.slice` is an int and handle that specifically:

``` python
    output_shape = list(input_shape)
    if isinstance(self.slice, int):
        del output_shape[self.axis]
    else:
        output_shape[self.axis] = len(range(*self.slice.indices(input_shape[self.axis])))
    return tuple(output_shape)
```

That `len(range(...))` part could still be changed to be more efficient in Python 2, either by using `xrange` in that case, or by computing the length of the range manually from the `start`, `stop` and `step` returned by `self.slice.indices`:

``` python
    else:
        start, stop, step = self.slice.indices(input_shape[self.axis])
        slice_size = something something
        output_shape[self.axis] = slice_size
```

**Comment by skaae** [comment]
Thanks, that works. I dont think the `len(range(...))` matters in practice. So unless you feel strongly for that i'll leave it as it is?

**Comment by skaae** [comment]
PR to lasagne in https://github.com/Lasagne/Lasagne/pull/255
