### ISSUE TITLE
Last merge seems to break variable length sequences RNN

### ISSUE THREAD

**Issue by PedroCardoso** [craffel/nntools#35]
Hi.

I was creating a tagging RNN for variable length sequences. 

The input layer was :
l_in = lasagne.layers.InputLayer(shape=(1, None, vocsize)) 

All the rest pretty much the same as the example. Except that I am not using mask

When I get to the cost, and with the last merge, I have an error:

```
cost = T.mean((lasagne.layers.get_output(l_out, input) - target_output)**2)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

Full stack 

```
----> 1 cost = T.mean((lasagne.layers.get_output(l_out, input) - target_output)**2)

/home/ubuntu/git/nntools/lasagne/layers/helper.py in get_output(layer_or_layers, inputs, **kwargs)
    226                                  "mapping this layer to an input expression."
    227                                  % layer)
--> 228             all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
    229     # return the output(s) of the requested layer(s) only
    230     try:

/home/ubuntu/git/nntools/lasagne/layers/recurrent.py in get_output_for(self, input, mask, **kwargs)
    162         # (seq_len*batch_size, num_inputs)
    163         input = T.reshape(input,
--> 164                           (self.seq_len*self.num_batch, -1))
    165         input_dot_W = helper.get_output(
    166             self.input_to_hidden, input, **kwargs)

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

code

```
    l_in = lasagne.layers.InputLayer(shape=(1, None, vocsize)) 
    l_forward = lasagne.layers.RecurrentLayer(l_in, N_HIDDEN, nonlinearity=None)
    l_backward = lasagne.layers.RecurrentLayer(l_in, N_HIDDEN, nonlinearity=None, backwards=True)
    l_sum = lasagne.layers.ElemwiseSumLayer([l_forward, l_backward])

    l_reshape = lasagne.layers.ReshapeLayer(l_sum, (-1, N_HIDDEN))

    l_recurrent_out = lasagne.layers.DenseLayer( l_reshape, num_units=nclasses, nonlinearity=softmax)
    l_out = lasagne.layers.ReshapeLayer( l_recurrent_out, (N_BATCH, -1, nclasses))

    print "Total parameters: {}".format(
                                        sum([p.get_value().size for p in lasagne.layers.get_all_params(l_out)]))

    input = T.tensor3('input')
    target_output = T.tensor3('target_output')

    #cost = T.mean((l_out.get_output(input) - target_output)**2)
    cost = T.mean((lasagne.layers.get_output(l_out, input) - target_output)**2)
```

**Comment by craffel** [comment]
Yes, this looks like it's because @skaae made it so that the input-to-hidden dot product is outside of the `scan`.  I think we can still allow this functionality by changing https://github.com/craffel/nntools/blob/master/lasagne/layers/recurrent.py#L163 to 

```
input = T.reshape((input, input.shape[0]*input.shape[1], -1))
```

instead of storing and using `self.seq_len` and `self.num_batch`.  The code, as it is, also I think would not allow for variable-size batches, which is something we want.  We also need to make pre-computing the input optional (as is done in the now semi-obsolete https://github.com/craffel/nntools/pull/25) as it incurs an additional memory requirement; I didn't notice this when merging the pull request.

**Comment by skaae** [comment]
Yes, didn't really consider that. We also need to change https://github.com/craffel/nntools/blob/master/lasagne/layers/recurrent.py#L216

Maybe to something like 

``` Python
hid_init = T.dot(T.ones((input.shape[0], 1)), self.hid_init)
```

EDIT: That would be for variable batch size :)

**Comment by craffel** [comment]
Yes, good point.  Do you want to do this or do you want me to?  I will be able to get to it once June starts.

**Comment by skaae** [comment]
Are you sure that variable sequence length would work at all? will scan unroll for different number of steps?

I can give it a try. We should probably fix this first and then i need to update the other PRs.

**Comment by skaae** [comment]
btw I cleaned some typos from the docs as well. Its mostly some cp errors that I made. 

I think the easiest is to  fix the batch/seq_len problem first, then merge https://github.com/craffel/nntools/pull/34 and afterwards i can create PR with the updated docs?

**Comment by craffel** [comment]
> Are you sure that variable sequence length would work at all?

Yes, I think it will.  I never actually used `None` as the time-step dimension, and I don't think it's a terribly good idea, but I can imagine some corner cases where it's better than using `mask`.

> I can give it a try.

Thanks.  I also just merged upstream.

> I think the easiest is to fix the batch/seq_len problem first, then merge #34 and afterwards i can create PR with the updated docs?

Sounds good.

**Comment by skaae** [comment]
I think https://github.com/craffel/nntools/pull/36 solves it?

@PedroCardoso Can you check? And thanks for pointing this out.

**Comment by PedroCardoso** [comment]
I will not have the time today, will test it later tomorrow, or over the weekend. Thanks

**Comment by PedroCardoso** [comment]
On a side note. Variable length  is needed for NLP tasks. We do not know a priory what is the size of a sentence.

I simply did not use mask, but if I understood well, you guys use it to indicate the "real" size of sequences, allowing multiple sizes with it ? In any case, this always limits the network to a maximum size.

**Comment by skaae** [comment]
Yes. Mask is used to indicate the real length and it allows different length sequences within the same batch. 

For a large text corpus, like wikipedia, there is no way you can process the entire dataset as a single 
sequence. In the penn tree example, see https://github.com/craffel/nntools/pull/33, I cut the corpus into equal length chunks. If you order the text-chunks appropriately you can use the previous batch as initialization to the next batch. In that case you can process sequences of any length. 

I'm not an expert on NLP though :)

**Comment by pedromnasc** [comment]
> Yes. Mask is used to indicate the real length and it allows different length sequences within the same batch.

But mask can be used in a sparse way (like "10101010111101")? 
Because as written here: 
`mask[i, j] = 1` when `j <= (length of sequence i)` and
  `mask[i, j] = 0` when `j > (length of sequence i)`.

It seems that the ones must come before the zeros. Right?

> For a large text corpus, like wikipedia, there is no way you can process the entire dataset as a single 
> sequence. In the penn tree example, see #33, I cut the corpus into equal length chunks. If you order the text-chunks appropriately you can use the previous batch as initialization to the next batch. In that case you can process sequences of any length.

I know nothing about this, but with this trick are the batches still processed in parallel by the GPU?

**Comment by skaae** [comment]
I think that there should be no problem with using sparse masks. Maybe the documentation is not that clear. I don't see the use case for sparse masks though? 

I dont see any problem with having 0's befor 1's. In that case all you do is copy the initial state to the first
non-masked sequence.

In an RNN the mask is used with:

```
hid_out = hid*mask_n + hid_previous*(1 - mask_n)
```

So if mask is zero then `hid_previous` is copied and if mask is 1 then `hid` is used.

**Comment by PedroCardoso** [comment]
It is working again. Thanks

**Comment by PedroCardoso** [comment]
One more question on the mask. If I have a batch of 5 and on the last set only 3 examples, would it work to leave the last two lines all at 0 ?

**Comment by craffel** [comment]
> One more question on the mask. If I have a batch of 5 and on the last set only 3 examples, would it work to leave the last two lines all at 0 ?

In that case, I'd suggest just making the batch size varible (setting the first dimension to `None`) instead.  Otherwise, you'll need to make up a fake target output for the non-existant training examples, and write a loss function which can mask whether to consider a training example or not.

**Comment by PedroCardoso** [comment]
Are all those variable sizes reducing the training speed. In the end, if I lose 3 to 4 training sequences out of 30 to 40K, it is not much .

**Comment by craffel** [comment]
I'm not sure.  There are circumstances where the speed will be decreased some, but as far as I know that's only with the convolutional layers, although there may be some Theano magic which makes that true for the recurrent layers (and/or in other places) too.  You can always profile to find out for sure!

If you are doing minibatch SGD, then you should be sampling your minibatches randomly at each epoch, so the 3 or 4 sequences that get missed on each epoch will be different, so in the end it's not such a big deal.
