### ISSUE TITLE
Add example with variable batchsize and sequence length

### ISSUE THREAD

**Issue by skaae** [craffel/nntools#44]
With  https://github.com/Lasagne/Lasagne/pull/287 you can construct  RNN's where both the batchsize and sequence length is variable. This is probably non obvious and i think we should add an example? 

Also see the comment in https://github.com/Lasagne/Lasagne/pull/287

**Comment by craffel** [comment]
Fixed by 005cae073891ec8f4185e8f1d5c40396a98435cf
