### ISSUE TITLE
Matrix multiplication in RecurrentLayer documentation

### ISSUE THREAD

**Issue by tristandeleu** [craffel/nntools#61]
In the `RecurrentLayer` documentation there is this expression

```
h_t = \sigma(W_x x_t + W_h h_{t-1} + b)
```

However `RecurrentLayer`, which uses `DenseLayer`, works with _post_-multiplications of the weight matrices (and treats `x_t` and `h_t` as row vectors). The actual matrix used to update the hidden state is `W_h^T` -- similarly for `W_x`.

There are two possible fixes (which is why I didn't make a PR right away, it all depends on your own preferences):
- Consider `x_t` and `h_t` as column vectors like in the documentation

```
h_t = \sigma(W_x^T x_t + W_h^T h_{t-1} + b)
```
- Consider `x_t` and `h_t` as row vectors like in the code

```
h_t = \sigma(x_t W_x + h_{t-1} W_h + b)
```

**Comment by craffel** [comment]
Sure.  The latter option is certainly better.

**Comment by tristandeleu** [comment]
It is indeed cleaner!
I haven't fully checked `LSTMLayer` and `GRULayer` but it looks like there are similar matrix multiplications issues there as well.

**Comment by craffel** [comment]
Fixed in af0b293b3f133744624b144b5bdc55259e81e310.

**Comment by tristandeleu** [comment]
I think it fixes #60 instead doesn't it?

**Comment by craffel** [comment]
Hm, maybe the commit hashes got messed up in a rebase.  It's 783e3d75ff80eb058e9907c47857f6b10332bc88 now.  Either way, it's fixed!

**Comment by tristandeleu** [comment]
Oh yes my bad, I just checked the commit history. Great! :)
