### ISSUE TITLE
in branch recurrent: TypeError: scan() got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by buriy** [craffel/nntools#64]
in branch recurrent, using example/recurrent.py :
TypeError: scan() got an unexpected keyword argument 'strict'

**Comment by craffel** [comment]
Which version of theano are you using? I would guess you're using an old version before the strict keyword arg was introduced, or something.

**Comment by buriy** [comment]
Thanks a lot! I had Theano v 0.6 installed.
