### ISSUE TITLE
Should we make layer to accept multiple input layers

### ISSUE THREAD

**Issue by gaoyuankidult** [craffel/nntools#8]
In many applications, we need to get input from multiple layers. However all layers in library only accepts one layer as previous input layer.

Should we make layer to accept multiple input layers?

**Comment by craffel** [comment]
Do you mean like these layers?
https://github.com/benanne/Lasagne/blob/720be55664bbbc3e87bfaed7602ff30d9d8f924e/lasagne/layers/merge.py

**Comment by gaoyuankidult** [comment]
Thanks ! It is really nice to know somebody has done that.
