### ISSUE TITLE
How to connect multiple recurrent layers?

### ISSUE THREAD

**Issue by JackKelly** [craffel/nntools#9]
Forgive me, this is a very basic question.  I'm just wondering how I should plug together multiple bidirectional LSTM layers (i.e. to create a deep BLSTM network)?  Specifically, I'm not sure exactly what combination of `ConcatLayer` and `ReshapeLayer` I need when I connect multiple BLSTM layers together.

Thanks again for your work on Lasagne... it's awesome stuff...

**Comment by JackKelly** [comment]
I assume it's as simple as this:

``` python
l_in = InputLayer(shape=input_shape)

# hidden LSTM layer 1
l_fwd1 = LSTMLayer(l_in, n_hidden, backwards=False, learn_init=True, peepholes=True)
l_bck1 = LSTMLayer(l_in, n_hidden, backwards=True, learn_init=True, peepholes=True)

# hidden LSTM layer 2
l_fwd2 = LSTMLayer(l_fwd1, n_hidden, backwards=False, learn_init=True, peepholes=True)
l_bck2 = LSTMLayer(l_bck1, n_hidden, backwards=True, learn_init=True, peepholes=True)

# concatenate forward and backward LSTM layers
concat_shape = (n_seq_per_batch * seq_length, n_hidden)
l_fwd_reshape = ReshapeLayer(l_fwd2, concat_shape)
l_bck_reshape = ReshapeLayer(l_bck2, concat_shape)
l_concat = ConcatLayer([l_fwd_reshape, l_bck_reshape], axis=1)

l_recurrent_out = DenseLayer(l_concat, num_units=n_outputs, nonlinearity=None)
l_out = ReshapeLayer(l_recurrent_out, output_shape)
```

**Comment by craffel** [comment]
Not quite, here's an example with 3 LSTM layers (of course, you could use a `ConcatLayer` instead of an `ElemwiseSumLayer` if you prefer):

``` Python
l_in = lasagne.layers.InputLayer(shape=(BATCH_SIZE, length, X_val.shape[-1]))

l_forward_1 = lasagne.layers.LSTMLayer(l_in, num_units=156)
l_backward_1 = lasagne.layers.LSTMLayer(l_in, num_units=156,
                                        backwards=True)
l_recurrent_1 = ElemwiseSumLayer(l_in, [l_forward_1, l_backward_1])

l_forward_2 = lasagne.layers.LSTMLayer(l_recurrent_1, num_units=300)
l_backward_2 = lasagne.layers.LSTMLayer(l_recurrent_1, num_units=300,
                                        backwards=True)
l_recurrent_2 = ElemwiseSumLayer(l_recurrent_1, [l_forward_2, l_backward_2])

l_forward_3 = lasagne.layers.LSTMLayer(l_recurrent_2, num_units=102)
l_backward_3 = lasagne.layers.LSTMLayer(l_recurrent_2, num_units=102,
                                        backwards=True)
l_recurrent_3 = ElemwiseSumLayer(l_recurrent_2, [l_forward_3, l_backward_3])

l_reshape = lasagne.layers.ReshapeLayer(l_recurrent_3,
                                       (BATCH_SIZE*length, 102))
nonlinearity = lasagne.nonlinearities.softmax
l_rec_out = lasagne.layers.DenseLayer(l_reshape, num_units=y_val.shape[-1],
                                      nonlinearity=nonlinearity)
l_out = lasagne.layers.ReshapeLayer(l_rec_out,
                                    (BATCH_SIZE, length, y_val.shape[-1]))
```

**Comment by JackKelly** [comment]
awesome, thank you for the very quick reply!

Two quick questions if I may:
1. what is `l_noise`?  I assume it's `l_noise = lasagne.layers.GaussianNoiseLayer(l_in, sigma=0.6)` (taken from your [LSTM Benchmark code](https://github.com/benanne/Lasagne/issues/17#issuecomment-68640150)?)
2. Can we do dropout with LSTM networks in Lasagne?  I remember there being a discussion about this between you and skaae over on the Lasagne issue queue.  Is it as simple as sticking a `DropoutLayer` after each `ElemwiseSumLayer`?   (I haven't gotten my network to overfit yet so I don't need dropout right now!)

Thanks again for everything ;)

**Comment by JackKelly** [comment]
Ah, I've found [your code example regarding Dropout](https://github.com/benanne/Lasagne/issues/17#issuecomment-69194705) over on the Lasagne issue queue ;).  That explains it.  I'll close this issue now, unless there's anything else to add?

**Comment by craffel** [comment]
> what is l_noise? I assume it's l_noise = lasagne.layers.GaussianNoiseLayer(l_in, sigma=0.6) (taken from your LSTM Benchmark code?)

Oops, yes, it's from the LSTM benchmark code; I tried to remove it but forgot that line (edited and fixed now).

> Can we do dropout with LSTM networks in Lasagne? I remember there being a discussion about this between you and skaae over on the Lasagne issue queue. Is it as simple as sticking a DropoutLayer after each ElemwiseSumLayer?

It depends on how you want to apply dropout.  You can place `DropoutLayer`s between layers as you say, but in [this paper](http://arxiv.org/pdf/1409.2329.pdf) they suggest that that's not a good idea, and instead it should only be applied to some LSTM connections. At this point, you can't do that in lasagne.

**Comment by JackKelly** [comment]
Cool, thank you.

**Comment by JackKelly** [comment]
Sorry to bother you again.  When I try `l_recurrent_1 = ElemwiseSumLayer(l_in, [l_forward_1, l_backward_1])` I get this error: `TypeError: 'InputLayer' object is not iterable`

I assume I should just do `l_recurrent_1 = ElemwiseSumLayer([l_forward_1, l_backward_1])`?  The call signature of the `ElemwiseSumLayer` constructor now appears to be `ElemwiseSumLayer(self, incomings, coeffs=1, **kwargs)`

**Comment by craffel** [comment]
Ah, sorry, the code I posted refers to a custom `ElemwiseSumLayer` I wrote... I probably should have tested that before I posted it.  Anyways, yes,

```
l_recurrent_1 = ElemwiseSumLayer([l_forward_1, l_backward_1])
```

is correct - although, as of now, this will cause certain computations to be computed multiple times.  See discussion here: https://github.com/benanne/Lasagne/issues/104

**Comment by JackKelly** [comment]
So, Theano has a bit of a heart attack if I do it in the way discussed above.  It spits out lots of `ValueError: graph contains cycles` exceptions. The full traceback is _long_ so I've put it into [this gist](https://gist.github.com/JackKelly/c2aa39a4fb77f46ba180) (I'm using the latest version of Theano from github as of a few minutes ago).

It seems to work OK if I forget about doing bi-directional LSTMs and instead just do this sort of thing:

``` python
l_lstm1 = LSTMLayer(l_in, 10)
l_lstm2 = LSTMLayer(l_lstm1, 10)
# ... then ReshapeLayer, DenseLayer and ReshapeLayer again
```

**Comment by craffel** [comment]
Can you post the code you're using?

**Comment by JackKelly** [comment]
Sure, here's my code:

``` python
l_in = InputLayer(shape=input_shape)

l_previous = l_in
# n_cells_per_hidden_layer is a list of integers.  Each integer
# specifies the number of LSTM cells for that hidden layer.
# The loop below should allow us to specify an arbitrary number
# of LSTM layers.
for n_cells in n_cells_per_hidden_layer:
    l_fwd = LSTMLayer(l_previous, n_cells, backwards=False,
                      learn_init=True, peepholes=True)
    l_bck = LSTMLayer(l_previous, n_cells, backwards=True,
                      learn_init=True, peepholes=True)
    l_previous = ElemwiseSumLayer([l_fwd, l_bck])
    # The lines above appear to cause `ValueError: graph contains cycles`.
    # If I replace the 5 lines above with the following then the
    # `graph contains cycles` error goes away:
    # l_previous = LSTMLayer(l_previous, n_cells, backwards=False,
    #                        learn_init=True, peepholes=True)

# concatenate forward and backward LSTM layers
concat_shape = (self.source.n_seq_per_batch * self.source.seq_length, 
                n_cells_per_hidden_layer[-1])
l_reshape = ReshapeLayer(l_previous, concat_shape)

l_recurrent_out = DenseLayer(l_reshape, num_units=self.source.n_outputs,
                             nonlinearity=output_nonlinearity)
l_out = ReshapeLayer(l_recurrent_out, output_shape)

input = T.tensor3('input')
target_output = T.tensor3('target_output')

# add test values
input.tag.test_value = rand(
    *input_shape).astype(theano.config.floatX)
target_output.tag.test_value = rand(
    *output_shape).astype(theano.config.floatX)

print("Compiling Theano functions...")
# Cost = mean squared error
cost = T.mean((l_out.get_output(input) - target_output)**2)
# Use NAG for training
all_params = lasagne.layers.get_all_params(l_out)
updates = lasagne.updates.nesterov_momentum(
    cost, all_params, learning_rate)

# Theano functions for training, getting output, and computing cost
self.train = theano.function(
    [input, target_output],
    cost, updates=updates, on_unused_input='warn',
    allow_input_downcast=True)

self.y_pred = theano.function(
    [input], l_out.get_output(input), on_unused_input='warn',
    allow_input_downcast=True)

self.compute_cost = theano.function(
    [input, target_output], cost, on_unused_input='warn',
    allow_input_downcast=True)

print("Done initialising network.")
```

**Comment by craffel** [comment]
This appears to only happen when `learn_init=True` and there is more than 1 stacked layer.  I'll create a separate issue for this.

**Comment by JackKelly** [comment]
cool, thanks for looking into this

**Comment by shiwangi27** [comment]
I have following question regarding joining Forward and Backward LSTM layers: 
1) I want to pass the resulting join to the next Forward and Backward LSTM layers. In case of ElemwiseSumLayer, doesn't it sum the two corresponding timesteps (say 1 with t, 2 with t-1, 3 with t-2 and so on). How will the structures be preserved in this case ? 

2) Will it be better to use ConcatLayer when I know the structure in the sequences is important to me ? What kind of operation does ConcatLayer do ? To elaborate my question, How does the next Forward (or Backward) LSTM layer get inputs from this Concatenated result ? Suppose I have 128 units each in my first BLSTM and 256 units each in the next ? How is the resulting concatenation passed from the first to the next BLSTM ? 

3) Are the connections sort of Dense between the two BLSTMs. Sorry I haven't seen any good architecture that explains how the stacked Bidirectional LSTMs share their inter layer connections. From the equations, I cannot get the gist of it.  

Best,
Shiwangi

**Comment by craffel** [comment]
Shiwangi, I don't really follow your questions, and this repository is a bit out of date (you should go to the main Lasagne repository for issues, and the lasagne-users mailing list for questions).  To try to answer your questions, the forward and backward LSTM layers process the sequence completely independently (they do not share parameters).  The forward LSTM processes the sequence in its original order, the backward LSTM processes the sequence reversed, and then its hidden states are reversed.  Using an elementwise add layer directly adds the hidden states  of the backwards and forwards LSTMs at a given time step.  Concatenating them just creates sequence of vectors each of shape 2*hidden_dim which has the forward LSTM layer's hidden state on top and backward on bottom.
